remote_theme: anydigital/bricks@v0.27.0-alpha.4
plugins:
  - jekyll-remote-theme
# theme: bricks

layouts_dir: _includes # 11ty parity
markdown: kramdown
kramdown:
  input: GFM
  extensions: [autolink]
